version: "3.8"

networks:
  bookshop:
    driver: bridge

services:
  order:
    image: "order-service"
    container_name: "order"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - SERVER_PORT=9001
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_KEYCLOAK_SERVER_URL=http://bookshop-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - bookshop


  image-gateway:
    image: "image-gateway-service"
    container_name: "image-gateway"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - SERVER_PORT=9002
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - SPRING_KEYCLOAK_SERVER_URL=http://bookshop-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - bookshop

  gateway:
    image: "gateway-service"
    container_name: "gateway"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - SERVER_PORT=9000
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - ORDER_SERVICE_URL=http://order:9001
      - IMAGE_GATEWAY_SERVICE_URL=http://image-gateway:9002
      - SPRING_REDIS_HOST=gateway-redis
      - SPRING_REDIS_PORT=6380
      - SPRING_KEYCLOAK_SERVER_URL=http://bookshop-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
    networks:
      - bookshop